dev tun
proto udp
port 1194
local 10.12.10.2

ifconfig 10.255.255.1 10.255.255.2
secret /etc/openvpn/static.key

cipher none
auth none

route 10.12.20.0 255.255.255.0

keepalive 10 60
persist-key
persist-tun
verb 4