dev tun
proto udp
remote 10.12.10.2 1194

ifconfig 10.255.255.2 10.255.255.1
secret /etc/openvpn/static.key

cipher none
auth none

route 10.12.10.0 255.255.255.0

keepalive 10 60
persist-key
persist-tun
verb 4