view "enterprise" {
  match-clients { enterprise-nets; };
  recursion yes;

  zone "enterprise.local" IN {
    type master;
    file "/etc/bind/zones/db.enterprise.local";
  };
};

view "residential" {
  match-clients { residential-nets; };
  recursion yes;

  zone "enterprise.local" IN {
    type master;
    file "/etc/bind/zones/db.enterprise.local.residential";
  };
};

view "default" {
  match-clients { any; };
  recursion no;
};
