view "client-view" {
  match-clients { poc-clients; };
  recursion yes;

  zone "poc.lab" IN {
    type master;
    file "/etc/bind/zones/db.poc.lab";
  };
};

view "default" {
  match-clients { any; };
  recursion no;
};
